### ISSUE TITLE
Doesn't Support Invector Ragdoll Multipliers

### ISSUE THREAD

**Issue by marcsantiago** [Black-Horizon-Studios/Emerald-AI#2]
RagDoll Multiplier don't work with this integration as is. The ragdoll.iChar  interface within the vDamageReceiver file is null when used in conjection with Emerald.  So I changed `if ((ragdoll && !ragdoll.iChar.isDead))` to  `if (ragdoll)` and added the below inside the if statement. This allowed for body part multipliers to work again.

  // Emerald AI Damage
 ```
  var ai = ragdoll.gameObject.GetComponentInParent<EmeraldAI.EmeraldAISystem>();
   if (ai) {
     ai.Damage(_damage.damageValue, EmeraldAI.EmeraldAISystem.TargetType.Player, transform);
   }
```

You also need a script to turn on all the colliders so that ragdoll with projectiles works.. For whatever reason Emerald AI turns off all the colliders in the mesh outside of the box collider they create, likewise the box collider that is create hides all the ragdoll components, so you'll want to shrink it to behind the ragdoll components if you want to control where body parts are hit.

example of what I did, just added it to a new monobehavior on the AI parent object at the end of the component list or after the emerald ai stuff.

```
private void Start()
{
        // turn on arms, legs etc
        foreach (var c in gameObject.GetComponentsInChildren<CapsuleCollider>()) {
            c.enabled = true;
        }
        
        // should only be one, the head.
        foreach (var c in gameObject.GetComponentsInChildren<SphereCollider>()) {
            c.enabled = true;
        }       
}
```

**Comment by Black-Horizon-Studios** [comment]
You need to use a [Location Based Damage](https://github.com/Black-Horizon-Studios/Emerald-AI/wiki/Using-Location-Based-Damage#using-location-based-damage) component on your AI to have colliders active during runtime. This section will also cover how to damage a Location Based Damage area.
