### ISSUE TITLE
Feature Request: Hiding System

### ISSUE THREAD

**Issue by bluemanD** [Black-Horizon-Studios/Emerald-AI#5]
I don't know if this is already possible, but having a way to hide from an enemy would be great. Also maybe having an option to have the enemy know where the player is if the enemy sees the player hide.

**Comment by Black-Horizon-Studios** [comment]
There's already a system for this. Attach the AdvancedLineOfSight script to your AI.

**Comment by bluemanD** [comment]
Is there a way to check what the AI's current target is?

**Comment by Black-Horizon-Studios** [comment]
Please email me for support questions. 

You can find the current target within the EmealdAISystem script using the CurrentTarget variable or through the Emerald AI Events Manager. The API can be found here: https://github.com/Black-Horizon-Studios/Emerald-AI/wiki/Emerald-AI-API#getcombattarget

**Comment by bluemanD** [comment]
Thank you!
