### ISSUE TITLE
Turning animations issue

### ISSUE THREAD

**Issue by wajid-h** [Black-Horizon-Studios/Emerald-AI#6]
I have a 90 degrees turn animations for character in both directions, left and right, but the character [Emerald AI Character] does not play them correctly, the AI keeps rotating when the animations have stopped playing.

**Comment by Black-Horizon-Studios** [comment]
Please email me a video of the issue so I can get a better idea of what's happening. 

Usually when this happens you, need to increase the Turning Angle and lower the Turning Speed settings. These can be found under AI's Settings>Movement>Turn Settings.
